#!/bin/bash 

DEVICE=/dev/input/dualshock3
PID_FILE="/tmp/xboxdrv_pid$(echo $DEVICE | sed 's/\//_/g')"
CONFIG=/home/robin/.scripts/xboxdrv.conf
BASE_DIR=$(dirname $0)
LOGFILE=/tmp/xboxdrv_udev.log

echo "RUN: at `date` by `whoami` action: $ACTION \$1 $1 DEVNAME $DEVNAME" >> ${LOGFILE}
echo "PATH: " $0 >> $LOGFILE

# Set permissions so Steam cant default to it and forces to use modified input
function fixPerm () {
	chmod 600 $DEVICE
}

# Run xboxdrv and read out PID to file for termination later
function axisConf () {
	xboxdrv  --evdev $DEVICE -d -c ${BASE_DIR}/xboxdrv.conf >> ${LOGFILE} &
	PID=$!
	echo “$PID” > $PID_FILE
}

# When controller is 'added' by udev
if [[ “$ACTION” == “add” ]]; then
	fixPerm
	axisConf	
fi

# When disconnected 
if [[ “$ACTION” == “remove” ]]; then
	PID=$(cat $PID_FILE)
	kill -9 $PID 		#SIGKILL is needed because the xboxdrv process can get stuck
fi
