#!/bin/bash
VAGRANT_PATH="$HOME/vagrant"
DOTFILES_PATH="$HOME/.dotfiles"
#VIMWIKI=""
DST="$HOME/.backup/linux"
set -ex

START=$(date +%s)
#function fullbackup (){
#    rsync -aAXvu --delete --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/home/robin/.local/share/Trash/*","/home/robin/.cache/mozilla/*","/home/robin/.cache/spotify/*","/home/robin/.steam/*","/home/robin/Torrents/*","/home/robin/.lyrics/.conf/*","/home/robin/.xbmc/userdata/Thumbnails/*","/home/robin/.thumbnails/*","/home/robin/.local/share/Steam/*","/home/robin/Musik/*","/home/robin/Videos/*","/home/robin/VirtualBox\ VMs/*","/home/robin/Downloads/*","/home/robin/.cache/*","/var/cache/*"} /* "$1"
#}
function selectionbackup (){
    # Vagrant
    rsync -aAXvuz --exclude={".*/","*.box"} $VAGRANT_PATH $DST
    #rsync -aAXvu $VAGRANT_PATH $DST/vagrant
    # Dotfiles
    rsync -aAXvuz $DOTFILES_PATH/* $DST/dotfiles

}
selectionbackup
#FINISH=$(date +%s)
#echo "total time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds" | tee $1/"Backup from $(date '+%Y-%m-%d, %T, %A')"
