#!/bin/bash
# Keep HDBits wishlist in sync with IMDB's watchlist
# Login info is req and will be typed into a separte text file
#set -xe

# IMDB watchlist URL
imdb_url="http://www.imdb.com/user/ur5234692/watchlist"
imdb_list="/tmp/imdb_list"
hdb_list="/tmp/hdb_list"
config="watchlist.conf"

# Fetch login info
username=$(sed -rn 's|username=(.*)$|\1|p' $config)
passkey=$(sed -rn 's|passkey=(.*)$|\1|p' $config)

## Get IMDB watchlist url and filter out /<imdbID> -link
curl -s --location $imdb_url | sed -rn 's|^.*title/(.*)/\?ref.*$|\1|p' | uniq > $imdb_list

## Get HDBits wishlist data and sort out the wishlist ID and IMDB ID
curl -s -H "Content-Type: Application/json" \
    -d '{"username":"'$username'","passkey":"'$passkey'"}' \
    "https://hdbits.org/api/wishlist" |
    tr {} '\n' | sed -rn 's|"id":"([0-9]+)","imdb":"([0-9]+).*$|\1 \2|p' > $hdb_list

# Add wishlist ID and IMDB ID to ass-array
declare -A HDB_LIST
while read line; do
    id=$(echo $line | awk '{print $1}')
    imdb_id=$(echo $line | awk '{print $2}')
    HDB_LIST[$id]="$imdb_id"
done <${hdb_list}

## DELETION
# Check if movies has been removed from IMDB's watchlist and then remove from HDB-wishlist
for id in "${!HDB_LIST[@]}"; do
    if ! grep -q ${HDB_LIST[$id]} $imdb_list; then
        echo "Deleting movie.."
        curl -H "Content-Type: Application/json" \
            -d '{"username":"'$username'","passkey":"'$passkey'","id":"'$id'"}' \
            "https://hdbits.org/api/wishlistDel"
        echo -e "\n"
    fi
done

## ADDING
# Check if new movies has appeared in IMDB's watchlist and then add to HDBit's wishlist
while read imdb_id; do
    new_id=$(echo $imdb_id | sed -rn 's|^tt0+?(.*)|\1|p')
    if ! grep -q $new_id $hdb_list; then
        echo "Adding new movie.."
        curl -H "Content-Type: Application/json" \
            -d '{"username":"'$username'","passkey":"'$passkey'","imdb_id":"'$imdb_id'"}' \
            "https://hdbits.org/api/wishlistAdd"
        echo -e "\n"
    fi
done <$imdb_list
