#!/bin/sh
#wallpapers=$HOME/pics/wallpapers/desktop
wallpapers=$HOME/pics/wallpapers/desktop/1680x1050

while true; do
	find $wallpapers -type f \( -name '*.jpg' -o -name '*.png' \) -print0 |
		shuf -n1 -z | xargs -0 feh --bg-fill
	sleep 30m
done
