#!/bin/bash 

function HELP (){
	echo "Usage: blalal"
}

function addMe (){
	num=$(($1 + $2))
	echo $num
}
#function doIt (){
#if [[ -e $1 && $1 =~ ^[0-9]{4}$ ]]; then
#if [[ -e $1 && -e $2 ]]; then
#   echo "hej"
#fi
#}
#if [ $( ls etcdiff | wc -l ) -ge 22 ]; then
#   echo "Enough"
#else	
#   echo "Not enough"
#fi
   echo $(basename $0) 
#while getopts :clhr:m: flag; do
#   case $flag in
#    m) echo "OPTARG is $OPTARG"
#	;;
#    r) echo "-r removes: $OPTARG"
#	;;
#    l) echo "-l used: "
#	;;
#    h) HELP
#	;;	
#    *) HELP
#   esac
#   echo "OPTIND is $OPTIND"
#done

	
     

