#!/bin/bash
FORMAT=$(date +%d%H%M%S)
#FORMAT='%Y%m%d-%k%M%S_$wx$h.png'

if [ "$1" == "select" ]; then
	#scrot -s $FORMAT -e 'mv $f ~/.screenshots/'
	import ~/.screenshots/${FORMAT}_Selection.png
else
	scrot ${FORMAT}_Fullscreen.png -e 'mv $f ~/.screenshots/'
fi
